### PR TITLE
Fix semvar versioning in tcp-ping endpoint

### PR DESCRIPTION
**Pull request by lifeeth**

### CODE REVIEW

**Comment by Page-** [comment]
Do we know there are no users of the current endpoint?

**Comment by lifeeth** [comment]
@Page- Yes - Our docs point to the endpoint with v1 -> http://docs.resin.io/#/pages/runtime/supervisor-api.md#post-v1-tcp-ping

**Comment by pcarranzav** [comment]
LGTM

**Comment by Page-** [comment]
LGTM

**Pull request merged**
