### PR TITLE
Add iptables rules to allow resin-vpn named interface to be used by VPN

### PR DESCRIPTION
**Pull request by lifeeth**
Connects to #247

---
This change is [Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/248)

### CODE REVIEW

**Comment by pcarranzav** [comment]
Not  sure if we should conditionally allow tun0 or resin-vpn depending on which we use?
Otherwise LGTM

**Comment by lifeeth** [comment]
@pcarranzav I think for a really robust setup we should parse the openvpn config and figure out what to allow. Older configs mean tun* unfortunately.

**Comment by floion** [comment]
Just a heads-up, the resin-vpm changes have been merged in meta-resin

**Comment by pcarranzav** [comment]
Okay, since time presses let's merge this and add the conditional check as soon as possible.
I still think we can treat old configs as tun0, as users using that interface are edge cases (which will be already solved from meta-resin). What do you think @lifeeth ?

**Comment by lifeeth** [comment]
@pcarranzav sorry missed this - Sounds good. This is atleast as good as what was before.

**Pull request merged**
