### PR TITLE
202 fix prox and propagate proxy to dind

### PR DESCRIPTION
**Pull request by axbannaz**
connects to #202

---
This change is [Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/203)

### CODE REVIEW

**Comment by Page-** [comment]
ok to test

**Comment by pcarranzav** [comment]
@resin-jenkins test this please

**Comment by axbannaz** [comment]
Would you know what caused the failure? I do not have access to see the logs on your Jenkins.

**Comment by Page-** [comment]
Hey, so the failure was due to our jenkins not being set up properly to work with external repo PRs, I'm working on fixing this and will get the build to rerun once I've sorted it

**Comment by axbannaz** [comment]
Thanks for the update :)

**Comment by Page-** [comment]
Ok, tests have passed now :)

**Comment by axbannaz** [comment]
is everyone ok with this change?

**Comment by pcarranzav** [comment]
Sorry for the delay. LGTM. @Page- ?

**Comment by axbannaz** [comment]
Nice, thanks guys.

**Pull request merged**
