### PR TITLE
Deploy all archs by default to Resin

### PR DESCRIPTION
**Pull request by dfunckt**
This makes the deploy-to-resin script deploy all supported archs by default, unless one is specified via the command line.

Change-Type: patch

### CODE REVIEW

**Comment by dfunckt** [comment]
@pcarranzav good point -- updated.

**Comment by pcarranzav** [comment]
Some tests fail due to an ongoing incident on CircleCI, I'm retrying them.

**Comment by pcarranzav** [comment]
@dfunckt would you please rebase and merge after #491 is merged?

**Comment by dfunckt** [comment]
@pcarranzav I will if I'm around but it seems tests take a while (and some fail too), so if I'm not and you need this before Monday please go ahead and merge.

**Pull request merged**
