### PR TITLE
Add build info for armv5

### PR DESCRIPTION
**Pull request by nghiant2710**
[Review on Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/80)

### CODE REVIEW

**Comment by lifeeth** [comment]
*[Makefile, line 26 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/80#-K8PcAPeUtQ89pNwEL5h:-K8PcAPeUtQ89pNwEL5i:121799137) ([raw file](https://github.com/resin-io/resin-supervisor/blob/0125e86a6bc112454bdaa941b0f499b60cda8c04/Makefile#L26)):*
We can set the GOARM level here instead and have it set only for armel builds.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/80)*

**Comment by lifeeth** [comment]
*[gosuper/Dockerfile, line 6 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/80#-K8PbVlxDNIyGP8Gky6T:-K8PbVlxDNIyGP8Gky6U:1130582237) ([raw file](https://github.com/resin-io/resin-supervisor/blob/0125e86a6bc112454bdaa941b0f499b60cda8c04/gosuper/Dockerfile#L6)):*
We can set this also in the Makefile?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/80)*

**Comment by pcarranzav** [comment]
@resin-jenkins add to whitelist

**Comment by pcarranzav** [comment]
@Trong could you add a Changelog entry for this please?

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[Makefile, line 26 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/80#-K8PcAPeUtQ89pNwEL5h:-K8PgEY2lVMe7rpiFFpW:-366058469) ([raw file](https://github.com/resin-io/resin-supervisor/blob/0125e86a6bc112454bdaa941b0f499b60cda8c04/Makefile#L26)):*
I agree with @lifeeth, we can have the appropriate GOARM for each architecture. @nghiant2710

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/80#-:-K8Pl-bUX9FZvbjgCreT:-599891533)*

**Comment by lifeeth** [comment]
Reviewed 1 of 3 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/80)*

**Comment by pcarranzav** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Makefile, line 26 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/80#-K8PcAPeUtQ89pNwEL5h:-K8QgmQcOkUK1-aC6xMZ:865055460) ([raw file](https://github.com/resin-io/resin-supervisor/blob/0125e86a6bc112454bdaa941b0f499b60cda8c04/Makefile#L26)):*
(Done)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/80)*

**Comment by nghiant2710** [comment]
while pushing a commit to update comments, I find out that Pablo had done it. Thanks, @pcarranzav for taking care of this :+1:

**Comment by nghiant2710** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Makefile, line 26 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/80#-K8PcAPeUtQ89pNwEL5h:-K8RQ56TzKbYzKm7r5FQ:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/0125e86a6bc112454bdaa941b0f499b60cda8c04/Makefile#L26)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/80)*

**Comment by pcarranzav** [comment]
No worries @nghiant2710 (and sorry, should've pinged you after addressing the comments)

**Comment by lifeeth** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/80)*

**Pull request merged**
