### PR TITLE
Make deltas resilient to slow network and/or truncated delta files

### PR DESCRIPTION
**Pull request by petrosagg**
This fixes the issue where the delta file is downloaded very slowly and causes rsync to timeout

### CODE REVIEW

**Comment by pcarranzav** [comment]
Connects to https://github.com/resin-io/hq/issues/583

**Comment by pcarranzav** [comment]
(@petrosagg ping - or do you want me to take over to get this merged?)

**Comment by imrehg** [comment]
@petrosagg @pcarranzav ping on this, as the issues got mentioned on current devices quite a bit.

**Comment by pcarranzav** [comment]
@petrosagg I guess we can close this given what you're doing about deltas?

**Comment by pcarranzav** [comment]
Closing for now @petrosagg - but I'll not delete the branch until you confirm

**Pull request closed without merging**
