### PR TITLE
docs/API.md: Fix documentation command sent via the API proxy for POST /v1/update

### PR DESCRIPTION
**Pull request by horia-delicoti**

### CODE REVIEW

**Comment by pcarranzav** [comment]
@resin-jenkins add to whitelist

**Comment by horia-delicoti** [comment]
Commit message "Change-Type: patch" added.

**Comment by pcarranzav** [comment]
Thanks @horia-delicoti but I think you did something weird when you rebased? There's a "4.1.1" commit that shouldn't be there, could you `git rebase -i master` (after pulling) to update the branch to only include your commit?

**Comment by horia-delicoti** [comment]
@pcarranzav Yes, that was weird for me too. Rebased and should be all good now.

**Pull request merged**
