### PR TITLE
Use go 1.6.2 for gosuper, and use golang alpine for alpine images

### PR DESCRIPTION
**Pull request by pcarranzav**
connects to #176

---
This change is [Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/177)

### CODE REVIEW

**Comment by Page-** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Makefile, line 21 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/177#-KKnwgDExCi_IHxqawH-:-KKnwgDF2N9fZySw904-:-1612468048) ([raw file](https://github.com/resin-io/resin-supervisor/blob/5e6b00918907888040fa4b0a8630e50b78185110/Makefile#L21)):*
> ```Makefile
> 	IMAGE = "resin/$(ARCH)-supervisor:$(SUPERVISOR_VERSION)-alpine"
> 	DOCKERFILE = alpine.$(ARCH)
> 	GOSUPER_DOCKERFILE = Dockerfile.$(ARCH)
> ```

Shouldn't this be `.alpine` rather than `.$(ARCH)`?

---

*[Makefile, line 22 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/177#-KKnwoRH0xyKv14h23Yg:-KKnwoRIMfvl0Ker0RMz:-1859948815) ([raw file](https://github.com/resin-io/resin-supervisor/blob/5e6b00918907888040fa4b0a8630e50b78185110/Makefile#L22)):*
> ```Makefile
> 	DOCKERFILE = alpine.$(ARCH)
> 	GOSUPER_DOCKERFILE = Dockerfile.$(ARCH)
> 	GOBUILDER_TAG = $(SUPERVISOR_VERSION)-$(ARCH)
> ```

Same here, `-alpine` rather than `-$(ARCH)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/177)*

**Comment by pcarranzav** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[Makefile, line 21 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/177#-KKnwgDExCi_IHxqawH-:-KKnzC91jyVv5OMJ6xEU:745252600) ([raw file](https://github.com/resin-io/resin-supervisor/blob/5e6b00918907888040fa4b0a8630e50b78185110/Makefile#L21)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> Shouldn't this be `.alpine` rather than `.$(ARCH)`?
</details>
Duh, I meant to use BASE_DISTRO. Sorry, fixed.

---

*[Makefile, line 22 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/177#-KKnwoRH0xyKv14h23Yg:-KKnzFuLUbwpOOnTtL2z:1837334785) ([raw file](https://github.com/resin-io/resin-supervisor/blob/5e6b00918907888040fa4b0a8630e50b78185110/Makefile#L22)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> Same here, `-alpine` rather than `-$(ARCH)`?
</details>
Ibidem

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/177)*

**Comment by Page-** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 21 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/177#-KKnwgDExCi_IHxqawH-:-KKo4JMTbgZL4T9sAmiQ:1885503057) ([raw file](https://github.com/resin-io/resin-supervisor/blob/5e6b00918907888040fa4b0a8630e50b78185110/Makefile#L21)):*
<details><summary><i>Previously, pcarranzav (Pablo Carranza Vélez) wrote…</i></summary>
> Duh, I meant to use BASE_DISTRO. Sorry, fixed.
</details>
It needs to be specifically `-alpine` as it stands, since the check is `isdef BASE_DISTRO` rather than checking the value of `BASE_DISTRO`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/177)*

**Comment by pcarranzav** [comment]
Fixed @Page- - and now the build actually works

**Comment by Page-** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/177)*

**Comment by Page-** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app.coffee, line 54 \[r4\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/177#-KKt6zRqfmABcv8wWNox:-KKt6zRqfmABcv8wWNoy:-1222300093) ([raw file](https://github.com/resin-io/resin-supervisor/blob/8bfdf7770dd87f3b003d9fcf24ff57b8924f8fe9/src/app.coffee#L54)):*
> ```CoffeeScript
> 						ip_address: body.Data.IPAddresses.join(' ')
> 					)
> 			utils.gosuper.get('/v1/ipaddr', { json: true }, callback)
> ```

I'm surprised this doesn't use promises :S

---

*[src/utils.coffee, line 176 \[r4\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/177#-KKt7L5i1jlOcHae62cu:-KKt7L5i1jlOcHae62cv:126791639) ([raw file](https://github.com/resin-io/resin-supervisor/blob/8bfdf7770dd87f3b003d9fcf24ff57b8924f8fe9/src/utils.coffee#L176)):*
> ```CoffeeScript
> gosuperRequest = (method, endpoint, options, callback) ->
> 	if !options? or _.isFunction(options)
> 		callback = options
> ```

This has issues with `gosuper.get('/v1/purge', null, ->)`, it's probably better to use `(method, endpoint, options = {}, callback) ->` and then just `_.isFunction(options)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/177)*

**Pull request closed without merging**
