### PR TITLE
178 dind docker 1.10.3 rsync dropbear

### LINKED ISSUE #178: dind: Upgrade to Docker 1.10.3, add rsync and dropbear

### PR DESCRIPTION
**Pull request by lekkas**
Closes #178

---
This change is [Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/179)

### CODE REVIEW

**Comment by Page-** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Makefile, line 61 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyIV1iFJgIuTPAegci:-KKyIV1iFJgIuTPAegcj:-137355297) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/Makefile#L61)):*
> ```Makefile
> supervisor-dind:
> 
> ifeq ($(PASSWORDLESS_DROPBEAR),true)
> ```

Could this be `sed -i "s/\(ENV PASSWORDLESS_DROPBEAR\).*/\1 ${PASSWORDLESS_DROPBEAR}/" tools/dind/Dockerfile` ?

---

*[tools/dind/Dockerfile, line 1 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyI7mg7PebLa4v6aON:-KKyI7mg7PebLa4v6aOO:1620070897) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/tools/dind/Dockerfile#L1)):*
> ```Dockerfile
> FROM resin/resin-base:1
> ```

Might be worth updating to `resin/resin-base:2`

---

*[tools/dind/Dockerfile, line 21 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyGjOKQFH1pHbQ20Wx:-KKyGjOKQFH1pHbQ20Wy:-1894772103) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/tools/dind/Dockerfile#L21)):*
> ```Dockerfile
> RUN apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D \
> 	&& echo deb https://apt.dockerproject.org/repo debian-${RELEASE_NAME} main > /etc/apt/sources.list.d/docker.list \
> 	&& apt-get -y update || true \
> ```

There's no need for the `-y`s

---

*[tools/dind/Dockerfile, line 23 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyGnagzkVobZhaH2EM:-KKyGnagzkVobZhaH2EN:-2013324148) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/tools/dind/Dockerfile#L23)):*
> ```Dockerfile
> 	&& apt-get -y update || true \
> 	&& apt-get -y --force-yes install docker-engine=${DOCKER_VERSION}-0~${RELEASE_NAME} \
> 	&& apt-mark hold docker-engine \
> ```

No need to mark it as hold in a dockerfile

---

*[tools/dind/Dockerfile, line 24 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyGsxsbl2ei8CCh94A:-KKyGsxtRrwORMSJfyuW:-595439796) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/tools/dind/Dockerfile#L24)):*
> ```Dockerfile
> 	&& apt-get -y --force-yes install docker-engine=${DOCKER_VERSION}-0~${RELEASE_NAME} \
> 	&& apt-mark hold docker-engine \
> 	&& mkdir -p /etc/systemd/system/docker.service.d \
> ```

We can drop this right? We don't put anything in this dir

---

*[tools/dind/Dockerfile, line 30 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyHd_aK3Ewt0HyCZbj:-KKyHd_aK3Ewt0HyCZbk:-2120476362) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/tools/dind/Dockerfile#L30)):*
> ```Dockerfile
> 
> # Change os release to a resin-sync compatible one
> RUN sed -i 's/\(PRETTY_NAME=\).*/\1"ResinOS 1.2.1"/' /etc/os-release
> ```

Is it possible to differentiate this from a standard resin os, eg `ResinOS-dind 1.2.1` or `ResinOS 1.2.1+dind` or something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179)*

**Comment by lekkas** [comment]
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[Makefile, line 61 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyIV1iFJgIuTPAegci:-KKyN0UIglzFGaWE2vS0:2092513187) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/Makefile#L61)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> Could this be `sed -i "s/\(ENV PASSWORDLESS_DROPBEAR\).*/\1 ${PASSWORDLESS_DROPBEAR}/" tools/dind/Dockerfile` ?
</details>
Yeah absolutely, good point, done

---

*[tools/dind/Dockerfile, line 1 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyI7mg7PebLa4v6aON:-KKyN-dN0GcfGTYd5e4e:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/tools/dind/Dockerfile#L1)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> Might be worth updating to `resin/resin-base:2`
</details>
Done.

---

*[tools/dind/Dockerfile, line 21 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyGjOKQFH1pHbQ20Wx:-KKyMzhgD8-qbzFc3-Un:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/tools/dind/Dockerfile#L21)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> There's no need for the `-y`s
</details>
Done.

---

*[tools/dind/Dockerfile, line 23 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyGnagzkVobZhaH2EM:-KKyMz4RVQ45l69qXOcq:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/tools/dind/Dockerfile#L23)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> No need to mark it as hold in a dockerfile
</details>
Done.

---

*[tools/dind/Dockerfile, line 24 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyGsxsbl2ei8CCh94A:-KKyLf7wNgWbpiDWsD5U:1263645292) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/tools/dind/Dockerfile#L24)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> We can drop this right? We don't put anything in this dir
</details>
We do later on with

`COPY config/services/ /etc/systemd/system/`

---

*[tools/dind/Dockerfile, line 30 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyHd_aK3Ewt0HyCZbj:-KKyLvMBv8ZQ07CXGGKs:-1986110378) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/tools/dind/Dockerfile#L30)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> Is it possible to differentiate this from a standard resin os, eg `ResinOS-dind 1.2.1` or `ResinOS 1.2.1+dind` or something?
</details>
Yeap, resin sync scans for a semver version in `PRETTY_NAME`, so it will not be affected

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179)*

**Comment by Page-** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/dind/Dockerfile, line 24 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyGsxsbl2ei8CCh94A:-KKz5On2FukEypVb1iET:167499474) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/tools/dind/Dockerfile#L24)):*
<details><summary><i>Previously, lekkas (Kostas Lekkas) wrote…</i></summary>
> We do later on with
> 
> `COPY config/services/ /etc/systemd/system/`
> 
</details>
That doesn't require the folder to exist already though does it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179)*

**Comment by lekkas** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/dind/Dockerfile, line 24 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179#-KKyGsxsbl2ei8CCh94A:-KL05uxTfcsgX2syBHOz:176590487) ([raw file](https://github.com/resin-io/resin-supervisor/blob/536e9ca6ff6f6a29157584282c2d26e7587f4de7/tools/dind/Dockerfile#L24)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> That doesn't require the folder to exist already though does it?
</details>
You are right, it doesn't. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179)*

**Comment by Page-** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/179)*

**Pull request merged**
