### PR TITLE
Switch to aufs for the docker-in-docker development supervisor

### LINKED ISSUE #368: dind supervisor should use aufs
It's the storage driver for ResinOS 2.X so it makes more sense to use that for testing.

### PR DESCRIPTION
**Pull request by pcarranzav**
Change-Type: patch
Signed-off-by: Pablo Carranza Velez <pablo@resin.io>
Closes #368

### CODE REVIEW

**Comment by Page-** [comment]
@hedss do you know if this will play nicely in the devenv?

**Comment by pcarranzav** [comment]
I just checked and indeed it doesn't work :(
@hedss think we could add aufs support to the devenv?

**Comment by hedss** [comment]
@pcarranzav Yep, shouldn't be a big deal, will add an issue and try to get it done today.

**Comment by hedss** [comment]
@pcarranzav If you try with a fresh clone of the DevEnv, hopefully this will all now be sorted! Let me know if you've any issues.

**Comment by pcarranzav** [comment]
Looks like it works now, thanks @hedss !
@Page-, I would appreciate your review now

**Pull request merged**
