### PR TITLE
Always pull the base images when building

### PR DESCRIPTION
**Pull request by pcarranzav**

### CODE REVIEW

**Comment by Page-** [comment]
It probably makes sense to add `--pull` to the gosuper build as well

**Comment by pcarranzav** [comment]
Well that one uses the official golang so it should be more stable, it felt like overkill to always pull there

**Comment by pcarranzav** [comment]
Though actually scratch that, it does make sense as it should incorporate bugfixes.  Will do.

**Comment by Page-** [comment]
It only pulls if there's changes btw, so if there's no changes it's essentially a noop (other than checking the id matches)

**Comment by pcarranzav** [comment]
True, done

**Pull request merged**
