### PR TITLE
WIP: Rewrite in Go

### LINKED ISSUE #44: Rewrite the whole supervisor  in Go

### PR DESCRIPTION
**Pull request by pcarranzav**
Closes #44 
Still a long way to go, but here's so you have an idea of where we're headed with this

### CODE REVIEW

**Comment by Page-** [comment]
What are the plans for migrating from the current sqlite db to bolt for existing devices?

---

Reviewed 21 of 54 files at r1, 62 of 77 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[gosuper/application/application.go, line 59 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_6GilqiZ7j3PqGTxC:-K3_6GilqiZ7j3PqGTxD:967000991) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/application/application.go#L59)):_
The `/mnt/root/resin-data/%d` should probably be shared as a `app.getDataPath` func or something, as it's used in a bunch of places

---

_[gosuper/application/application.go, line 66 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_61ceaJClmoz93Qyu:-K3_61ceaJClmoz93Qyv:53928721) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/application/application.go#L66)):_
Generally I prefer `err` to `er`, mainly due to what I'm used to (`e` is also fine)

---

_[gosuper/application/application.go, line 69 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_6oE9rQPP84lbvHCU:-K3_6oE9rQPP84lbvHCV:-309969377) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/application/application.go#L69)):_
It might make sense to use the assign to return pattern for this

---

_[gosuper/config/config.go, line 101 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_83-vlKlG-uTkUdZF:-K3_83-vlKlG-uTkUdZG:-458127961) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/config/config.go#L101)):_
There's no need for the explicit return is there?

---

_[gosuper/device/device.go, line 25 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_DV267FxJBF-fWIuw:-K3_DV267FxJBF-fWIux:-367388514) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/device/device.go#L25)):_
Should this be just an `=`?

---

_[gosuper/device/device.go, line 34 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_DG4WEfwH5x_b3EzN:-K3_DG4WEfwH5x_b3EzO:427177571) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/device/device.go#L34)):_
Would `return readConfigAndEnsureUuid(superConfig)` work? It would make the recursion much clearer to me at least.

---

_[gosuper/device/device.go, line 62 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_BrJEEYsfG_1O55D_:-K3_BrJEEYsfG_1O55Da:-691285635) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/device/device.go#L62)):_
This uses `:=`, will it be properly returned as the error response in that case? (ie should it be just `=`?)

---

_[gosuper/Dockerfile, line 10 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_Dhp_GrzhYUOydMJ0:-K3_Dhp_GrzhYUOydMJ1:-1912418793) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/Dockerfile#L10)):_
Can these be combined into one `RUN`? Or would it be possible to set the +x flag on the git index and not need to have the chmods here?

---

_[gosuper/gosuper/api.go, line 42 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_ER_0YZNBwJl-_9mw:-K3_ER_0YZNBwJl-_9mx:1857044260) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/gosuper/api.go#L42)):_
Where does the status code get set?

---

_[gosuper/gosuper/api.go, line 60 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_EeivZC05psXavWC-:-K3_EeivZC05psXavWC0:-977581337) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/gosuper/api.go#L60)):_
I don't like seeing supervisor exiting, what is in charge of making sure things continue to work?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-:-K3_Jp4U0DLVUeEtI7Cf:-1122583785)_

**Comment by lorenzo-stoakes** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[gosuper/config/config.go, line 101 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_83-vlKlG-uTkUdZF:-K3_MZqkEb1eFkHGLGTJ:-1642209573) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/config/config.go#L101)):_
Yeah there is, as he's returning `config`, using some nifty syntax. So:

```go
func foo() (ret bar) {
    ret = getBar()

    return
}
```

Is equivalent to:

```go
func foo() bar {
    return getBar()
}
```

Usually you'd use it when you have multiple return values like:

```go
func blah(a, b int, c string) {
    a = 5
    // some other code...
    c = "hi"

    return
}
```

(Note that unassigned values are assigned their default values, which in go are automatically zeroed thankfully!)

Pablo is using it here to nice effect in order to use `populateConfig` to assign to `config` without having to explicitly do:

```go
func GetSupervisorConfig() SupervisorConfig {
    var config SupervisorConfig    

    populateConfig(&config)
    return config
}
```

This sugar simply adds the equivalent of the variable declaration for you, and automatically converts a `return` into what's needed.

In any case go requires you to explicitly return to make it clear that this function does in fact return and differentiate it from void functions (there might be other reasons for this also.)

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14)_

**Comment by Page-** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[gosuper/config/config.go, line 101 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_83-vlKlG-uTkUdZF:-K3_VULJpXL42nM11Sp9:2058178311) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/config/config.go#L101)):_
Wait, so am I right in thinking that the return is necessary because the assign does not by itself does not mean they get returned, it just means they are what will get returned if you add an explicit `return` statement?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14)_

**Comment by pcarranzav** [comment]
Still undecided... but I'm thinking of a shell script that dumps the DB to a CSV, and then picking that up during bootstrap. Any other ideas?

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[gosuper/config/config.go, line 101 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_83-vlKlG-uTkUdZF:-K3_eHp3wx0n1I6dmjuI:-1330776432) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/config/config.go#L101)):_
It's just golang's verbose nature; it will error out if there's no return statement in a function that returns values

---

_[gosuper/device/device.go, line 25 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_DV267FxJBF-fWIuw:-K3_eT5HXpCLIFunO7MH:-1184231930) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/device/device.go#L25)):_
Since userConfig is not defined, we need the `:=`

---

_[gosuper/device/device.go, line 34 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_DG4WEfwH5x_b3EzN:-K3_eYmSk-LbFyAoyG4S:1745782712) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/device/device.go#L34)):_
AFAIK no, since we have named return variables, we have to assign them

---

_[gosuper/device/device.go, line 62 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_BrJEEYsfG_1O55D_:-K3_ed8hX-TZxSZC3t7O:782706010) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/device/device.go#L62)):_
The `:=` will only create the variables that are still undefined

---

_[gosuper/gosuper/api.go, line 42 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_ER_0YZNBwJl-_9mw:-K3_fG17rCEbi97UnQRP:-1539105195) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/gosuper/api.go#L42)):_
If we don't explicitly do a WriteHeader, the 200 code will be added on the first write to the response. See [here](https://golang.org/pkg/net/http/#ResponseWriter)

---

_[gosuper/gosuper/api.go, line 60 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_EeivZC05psXavWC-:-K3_fRduPMxpBdWCm01E:629209398) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/gosuper/api.go#L60)):_
True, I will go through all of these Fatals and change them

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-:-K3_dIqFpUJSaivaql8f:-1765154887)_

**Comment by Page-** [comment]
Not really, I just want to make sure it gets considered/handled

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[gosuper/device/device.go, line 34 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_DG4WEfwH5x_b3EzN:-K3_tvwJuAPoJDtBwVfb:-485513921) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/device/device.go#L34)):_
Shame

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-:-K3_uIQ4wdCyNT5-_h-n:108474093)_

**Comment by pcarranzav** [comment]
Review status: 75 of 81 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[gosuper/device/device.go, line 34 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_DG4WEfwH5x_b3EzN:-K3b0eJi5pssW3aSprpi:-2124280570) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/device/device.go#L34)):_
You were right on this one.

---

_[gosuper/device/device.go, line 62 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_BrJEEYsfG_1O55D_:-K3b0ZAS_JWKsjmAjrvw:1142365776) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/device/device.go#L62)):_
I think you were actually right on this one

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14)_

**Comment by pcarranzav** [comment]
@resin-jenkins test this please

**Comment by Page-** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[gosuper/application/application.go, line 58 \[r3\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3nwI1RcdiEn_E2rulU:-K3nwI1RcdiEn_E2rulV:2024266423) ([raw file](https://github.com/resin-io/resin-supervisor/blob/2724063c5a959d3aa3d0c7f409e0dafca8ecc526/gosuper/application/application.go#L58)):_
Can't this be `func (app supermodels.App) DataPath() string {` and be called as `app.DataPath()`?  It just feels like a better structuring to have the app generate its data (and other) paths rather than the manager

---

_[gosuper/device/device.go, line 92 \[r3\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3nvkv-Q95gYhF3qvE9:-K3nvkv-Q95gYhF3qvEA:-520483256) ([raw file](https://github.com/resin-io/resin-supervisor/blob/2724063c5a959d3aa3d0c7f409e0dafca8ecc526/gosuper/device/device.go#L92)):_
If I understand https://golang.org/pkg/builtin/#append correctly this should be `dev.waitChannels = append(dev.waitChannels, make(chan bool))`?

---

_[gosuper/gosuper/main.go, line 19 \[r3\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3nwwmcTFYfSEKaH06u:-K3nwwmcTFYfSEKaH06v:1596730785) ([raw file](https://github.com/resin-io/resin-supervisor/blob/2724063c5a959d3aa3d0c7f409e0dafca8ecc526/gosuper/gosuper/main.go#L19)):_
I was a bit confused by this (briefly thought it was saying "wait for ever", who/what is ever?) - can this be `waitForever` please

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14)_

**Comment by discordianfish** [comment]
Hi, hope you don't mind some nitpicking. Here are a few thoughts/suggestions I have after looking at the code:

- Avoid nesting by returning early
  - Arguably it's much more readable but it's definitely Go idiomatic: https://golang.org/doc/effective_go.html#if
- Use Go native vendoring instead of Godeps: https://golang.org/cmd/go/#hdr-Vendor_Directories
- Avoid naked returns especially if function is more than a few lines
  - Named return values are fine but should be mainly used for documentation purposes: https://github.com/golang/go/wiki/CodeReviewComments#named-result-parameters
- Move binary from gosuper/ to cmd/gosuper
  - technically gosuper/ is fine (all is, as long as it's not in the root of the repo) but go itself organizes the binaries this way[1] and and a lot of projects do the same (and consistency rocks)
- Use golint

1) https://github.com/golang/go/tree/master/src/cmd

**Comment by Page-** [comment]
Reviewed 1 of 77 files at r2, 1 of 5 files at r4, 200 of 205 files at r5, 7 of 9 files at r6, 3 of 5 files at r7, 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[gosuper/config/config.go, line 118 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCaVPZIrVhobs5_aKwF:-KCaVPZIrVhobs5_aKwG:16740104) ([raw file](https://github.com/resin-io/resin-supervisor/blob/ee1903b87c5a8ea25508aff9edbdd171f6a97564/gosuper/config/config.go#L118)):*
I understand this is a direct translation, but I feel with a full golang supervisor we might not have a package.json :P  Is there a golang standard for specifying the version?

---

*[gosuper/resin/resin.go, line 21 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCaTb2qQr-G676RX6eY:-KCaTb2rzXjZBMpRBEoX:-1999409717) ([raw file](https://github.com/resin-io/resin-supervisor/blob/ee1903b87c5a8ea25508aff9edbdd171f6a97564/gosuper/resin/resin.go#L21)):*
It'd be worth targeting `/v1`

---

*[gosuper/resin/resin.go, line 35 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCaTjwdHQ7LwH8nH3TM:-KCaTjwdHQ7LwH8nH3TN:-24212800) ([raw file](https://github.com/resin-io/resin-supervisor/blob/ee1903b87c5a8ea25508aff9edbdd171f6a97564/gosuper/resin/resin.go#L35)):*
`uuid` should be escaped - but it makes more sense to build that into pinejs-client-go rather than do it manually here

---

*[gosuper/resin/resin.go, line 35 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCaUBxYtAOoo0HZB1mO:-KCaUBxYtAOoo0HZB1mP:-1287462099) ([raw file](https://github.com/resin-io/resin-supervisor/blob/ee1903b87c5a8ea25508aff9edbdd171f6a97564/gosuper/resin/resin.go#L35)):*
The quotes in odata should be `'` not `"`

---

*[gosuper/resin/resin.go, line 47 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCaTxU1DXSzn411nLmj:-KCaTxU1DXSzn411nLmk:-252937800) ([raw file](https://github.com/resin-io/resin-supervisor/blob/ee1903b87c5a8ea25508aff9edbdd171f6a97564/gosuper/resin/resin.go#L47)):*
`device.uuid` should be `device/any(d:d/uuid eq ...)`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14)*

**Comment by pcarranzav** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[gosuper/Dockerfile, line 10 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_Dhp_GrzhYUOydMJ0:-KCb4VoYoqEX9HvCuG3H:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/Dockerfile#L10)):*
Done.

---

*[gosuper/application/application.go, line 59 \[r2\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3_6GilqiZ7j3PqGTxC:-KCb4SVwr4u9m2zwIBwg:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/a7151492613141495adc4fbfb353792a99b883a9/gosuper/application/application.go#L59)):*
Done.

---

*[gosuper/device/device.go, line 92 \[r3\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3nvkv-Q95gYhF3qvE9:-KCb4ODalWeGac3lTf3b:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/2724063c5a959d3aa3d0c7f409e0dafca8ecc526/gosuper/device/device.go#L92)):*
Done.

---

*[gosuper/gosuper/main.go, line 19 \[r3\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3nwwmcTFYfSEKaH06u:-KCb4MMkpfJ83oG5_Zrn:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/2724063c5a959d3aa3d0c7f409e0dafca8ecc526/gosuper/gosuper/main.go#L19)):*
Done.

---

*[gosuper/resin/resin.go, line 21 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCaTb2qQr-G676RX6eY:-KCb4H6jJV8CgwbuPFIc:1866474071) ([raw file](https://github.com/resin-io/resin-supervisor/blob/ee1903b87c5a8ea25508aff9edbdd171f6a97564/gosuper/resin/resin.go#L21)):*
`/v1/ewa` or `/ewa/v1`?

---

*[gosuper/resin/resin.go, line 35 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCaTjwdHQ7LwH8nH3TM:-KCb4EVNcjVH9IaIZhW8:-131033743) ([raw file](https://github.com/resin-io/resin-supervisor/blob/ee1903b87c5a8ea25508aff9edbdd171f6a97564/gosuper/resin/resin.go#L35)):*
escaped how?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14)*

**Comment by pcarranzav** [comment]
Review status: 278 of 279 files reviewed at latest revision, 10 unresolved discussions.

---

*[gosuper/resin/resin.go, line 35 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCaUBxYtAOoo0HZB1mO:-KCb5KHYTpaBwx7kIBRE:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/ee1903b87c5a8ea25508aff9edbdd171f6a97564/gosuper/resin/resin.go#L35)):*
Done.

---

*[gosuper/resin/resin.go, line 47 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCaTxU1DXSzn411nLmj:-KCb5E0SdmiNKm0j8UnO:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/ee1903b87c5a8ea25508aff9edbdd171f6a97564/gosuper/resin/resin.go#L47)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14)*

**Comment by Page-** [comment]
Review status: 278 of 279 files reviewed at latest revision, 6 unresolved discussions.

---

*[gosuper/device/device.go, line 92 \[r3\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3nvkv-Q95gYhF3qvE9:-KCq2ET0YSrCPquezLO7:120413347) ([raw file](https://github.com/resin-io/resin-supervisor/blob/2724063c5a959d3aa3d0c7f409e0dafca8ecc526/gosuper/device/device.go#L92)):*
We just ignore the result? I thought the result was the appended version, with the input left without any mutation?

---

*[gosuper/resin/resin.go, line 21 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCaTb2qQr-G676RX6eY:-KCq1qxhg1yv9MDk0ZQx:1260555309) ([raw file](https://github.com/resin-io/resin-supervisor/blob/ee1903b87c5a8ea25508aff9edbdd171f6a97564/gosuper/resin/resin.go#L21)):*
`client.Client = *(pinejs.NewClient(apiEndpoint+"/v1", apiKey))`

---

*[gosuper/resin/resin.go, line 35 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCaTjwdHQ7LwH8nH3TM:-KCq1djZxPkKabue2MUh:-420106918) ([raw file](https://github.com/resin-io/resin-supervisor/blob/ee1903b87c5a8ea25508aff9edbdd171f6a97564/gosuper/resin/resin.go#L35)):*
This is the pinejs-client-js function for esacping the value: https://github.com/resin-io/pinejs-client-js/blob/bd14e738ae55f64700956f06a79282a7f10276ad/core.coffee#L43-L50

---

*[gosuper/resin/resin.go, line 47 \[r9\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCq1QKQXzXSxIcpFqSn:-KCq1QKQXzXSxIcpFqSo:-2065952879) ([raw file](https://github.com/resin-io/resin-supervisor/blob/2f323376851262c8f641e088a7b121d667c5b32c/gosuper/resin/resin.go#L47)):*
There needs to be a space between `eq` and `'`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14)*

**Comment by pcarranzav** [comment]
Review status: 278 of 279 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[gosuper/application/application.go, line 58 \[r3\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-K3nwI1RcdiEn_E2rulU:-KDdqOHHzPuQO7S1MtfB:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/2724063c5a959d3aa3d0c7f409e0dafca8ecc526/gosuper/application/application.go#L58)):*
Done.

---

*[gosuper/resin/resin.go, line 21 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14#-KCaTb2qQr-G676RX6eY:-KDdqazP5Cr_txDSlr1i:-742065548) ([raw file](https://github.com/resin-io/resin-supervisor/blob/ee1903b87c5a8ea25508aff9edbdd171f6a97564/gosuper/resin/resin.go#L21)):*
@Page- is the /environment endpoint also versioned now?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/14)*

**Comment by pcarranzav** [comment]
Closing this as we decided to re-architecture and progressively refactor/improve the supervisor instead of rewriting from scratch.

**Pull request closed without merging**
