### PR TITLE
Deploy supervisor to the Resin registry too

### PR DESCRIPTION
**Pull request by pcarranzav**
[Review on Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/15)

### CODE REVIEW

**Comment by Page-** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/15)_

**Comment by Page-** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/15)_

**Comment by lifeeth** [comment]
LGTM

**Comment by lifeeth** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/15)*

**Comment by pcarranzav** [comment]
@resin-jenkins test this please

**Comment by lifeeth** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/15)*

**Pull request merged**
