### PR TITLE
Expose resin API key to apps

### PR DESCRIPTION
**Pull request by pcarranzav**
connects to #18

[Review on Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/86)

### CODE REVIEW

**Comment by abresas** [comment]
Code-wise LGTM.

**Comment by jviotti** [comment]
LGTM. Maybe the fact that the API key is exposed as `RESIN_API_KEY` should be documented in the README?

**Comment by petrosagg** [comment]
SGTM

**Comment by pcarranzav** [comment]
@jviotti I just created #87 for this.

**Pull request merged**
