### PR TITLE
WIP: Add stop, start and get app endpoints

### PR DESCRIPTION
**Pull request by pcarranzav**
connects to #129 

This change is [Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/126)

### CODE REVIEW

**Comment by lorenzo-stoakes** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/api.coffee, line 174 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFoL-vwWxfOmQSymGJS:-KFoL-vwWxfOmQSymGJT:-2052446967) ([raw file](https://github.com/resin-io/resin-supervisor/blob/cca41e8271da028a035b7f933fbf5bf450c6b641/src/api.coffee#L174)):*
I think it's a bit risky having a hard-coded omission list here, what if we add further keys we want to exclude later? Best to at least abstract elsewhere I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Comment by lorenzo-stoakes** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/api.coffee, line 131 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFoLDAISDFF-zGDGHsW:-KFoLDAJ2vF_h5towvnX:1369415996) ([raw file](https://github.com/resin-io/resin-supervisor/blob/cca41e8271da028a035b7f933fbf5bf450c6b641/src/api.coffee#L131)):*
Very minor tip - you can do `{ appId } = req.params` which achieves the same thing, just a bit nicer :) applies to `force` below too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Comment by lorenzo-stoakes** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/api.coffee, line 143 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFoLRFIth8yHvfvqLeR:-KFoLRFIth8yHvfvqLeS:-777188972) ([raw file](https://github.com/resin-io/resin-supervisor/blob/cca41e8271da028a035b7f933fbf5bf450c6b641/src/api.coffee#L143)):*
Another real nit, there's some inconsistency in spacing here, generally put a space after `[` and before `]`. There are some other inconsistencies around the PR like this, so I'll only mention it once but applies to all cases :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Comment by lorenzo-stoakes** [comment]
Reviewed 1 of 3 files at r2, 1 of 1 files at r8.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Comment by lorenzo-stoakes** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/application.coffee, line 119 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFoM6ejko48nR9B7v0U:-KFoM6ejko48nR9B7v0V:-926486945) ([raw file](https://github.com/resin-io/resin-supervisor/blob/cca41e8271da028a035b7f933fbf5bf450c6b641/src/application.coffee#L119)):*
If you're just unconditionally returning below, you can omit the `return` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Comment by lekkas** [comment]
Reviewed 1 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/api.coffee, line 174 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFoL-vwWxfOmQSymGJS:-KFoPBswI7GvD5p3MBcn:1193317399) ([raw file](https://github.com/resin-io/resin-supervisor/blob/cca41e8271da028a035b7f933fbf5bf450c6b641/src/api.coffee#L174)):*
For the time being, the only information that we really need from this endpoint is the container Id. I agree with your point, though at the moment I'd rather push the abstraction problem a bit further into the future and instead `_.pick()` the containerId explicitly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Comment by lorenzo-stoakes** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/api.coffee, line 174 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFoL-vwWxfOmQSymGJS:-KFoRRgvs15HWqdI3kpd:-452697144) ([raw file](https://github.com/resin-io/resin-supervisor/blob/cca41e8271da028a035b7f933fbf5bf450c6b641/src/api.coffee#L174)):*
I think if a user is trying to get details about the `app` they will want more than container ID, rather as much information as possible so an `omit` seems appropriate. 

A simple approach for the time being might be to make this and the below omit into 'constants' (well capitalised variable names anyway :) and put them at the top of the file then reference them here. This makes it explicit that you are referencing these vars and makes the hardcoded list less easily lost in the noise.

This means that consideration can be deferred for now, though you really ought to create an issue for this so it's not forgotten!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Comment by lekkas** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/api.coffee, line 174 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFoL-vwWxfOmQSymGJS:-KFoYcPUlWyxRsA3wRF-:612150223) ([raw file](https://github.com/resin-io/resin-supervisor/blob/cca41e8271da028a035b7f933fbf5bf450c6b641/src/api.coffee#L174)):*
Makes sense. I used a list (camel-cased, to be consistent with `src/application.coffee` which I noticed also uses `_.omit()` at some point) to specify the data to be omitted. Also created an issue (https://github.com/resin-io/resin-supervisor/issues/132) to track it in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Comment by lorenzo-stoakes** [comment]
Reviewed 1 of 2 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Comment by Page-** [comment]
Reviewed 1 of 3 files at r2, 1 of 1 files at r8, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/api.coffee, line 174 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFoL-vwWxfOmQSymGJS:-KFpYpeYynRcR0VyGGdd:-547228139) ([raw file](https://github.com/resin-io/resin-supervisor/blob/cca41e8271da028a035b7f933fbf5bf450c6b641/src/api.coffee#L174)):*
The problem with the hardcoded omit is what if they need to add api keys or other sensitive info? Then anyone who can query the device can query that info can't they? (Or do we only bind to localhost/vpn?)

---

*[src/api.coffee, line 154 \[r10\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFpZJs5UtLhlqJHV80l:-KFpZJs5UtLhlqJHV80m:-715554611) ([raw file](https://github.com/resin-io/resin-supervisor/blob/f76b38eb49b3d820e4d27589bb7aa07e7e98d24e/src/api.coffee#L154)):*
This can be `res.json(_.pick(app, 'containerId'))`

---

*[src/api.coffee, line 170 \[r10\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFpYZKkYQzWfEXqHVdl:-KFpYZKlIbZfAAmThNGN:-715554611) ([raw file](https://github.com/resin-io/resin-supervisor/blob/f76b38eb49b3d820e4d27589bb7aa07e7e98d24e/src/api.coffee#L170)):*
This can be `res.json(_.pick(app, 'containerId'))`

---

*[src/api.coffee, line 187 \[r10\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFpZCIXTf505o_8vsCf:-KFpZCIYkbbjXei9Nq3I:-1747160428) ([raw file](https://github.com/resin-io/resin-supervisor/blob/f76b38eb49b3d820e4d27589bb7aa07e7e98d24e/src/api.coffee#L187)):*
Can't we do this better by having the fields we want to select in the select statement?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Comment by lekkas** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/api.coffee, line 174 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFoL-vwWxfOmQSymGJS:-KFoZtY30VoUYgc6p1Oq:1153052228) ([raw file](https://github.com/resin-io/resin-supervisor/blob/cca41e8271da028a035b7f933fbf5bf450c6b641/src/api.coffee#L174)):*
Yeah that's true. Any non-omitted environment will be fetched and this potentially includes API keys. Also I checked and we bind to all interfaces - I had the impression we only bound to localhost btw. In any case, one would need the supervisor API key to make queries, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Comment by Page-** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/api.coffee, line 174 \[r8\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126#-KFoL-vwWxfOmQSymGJS:-KFtxlE1ByaJSwsUxUo7:-273951448) ([raw file](https://github.com/resin-io/resin-supervisor/blob/cca41e8271da028a035b7f933fbf5bf450c6b641/src/api.coffee#L174)):*
Yeah, I think that it's ok with that, @petrosagg does that sound ok to you?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Comment by lekkas** [comment]
Reviewed 1 of 1 files at r8, 1 of 2 files at r9, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/126)*

**Pull request merged**
