### PR TITLE
Makefile: removed the deprecated force flag

### PR DESCRIPTION
**Pull request by zozo123**
Since docker 1.10 the -f option of docker tag
is obsolete. In docker 1.12 it is completely
removed.

https://docs.docker.com/engine/deprecated/#/f-flag-on-docker-tag

Signed-off-by: Yossi Eliaz <yossi@resin.io>

### CODE REVIEW

**Comment by Page-** [comment]
add to whitelist

**Comment by Page-** [comment]
I don't think this can be removed yet, as it won't work on many versions of docker

**Comment by pcarranzav** [comment]
As Page says, we can't do this yet, at least until Jenkins has docker > 1.10.

**Comment by zozo123** [comment]
@pcarranzav @Page- Please see the new and hopefully better solution.

**Comment by zozo123** [comment]
Fixed.

**Pull request merged**
