### PR TITLE
Only save the app if starting the container was successful

### PR DESCRIPTION
**Pull request by pcarranzav**
Connects to #37 

[Review on Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/38)

### CODE REVIEW

**Comment by pcarranzav** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/application.coffee, line 223 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/38#-K4ZGv4ynq1ApVcAb8wy:-K4ZGv4ynq1ApVcAb8wz:464032539) ([raw file](https://github.com/resin-io/resin-supervisor/blob/f0afdb9b2a04b5da39420eaafea34be3a188bf08/src/application.coffee#L223)):*
Might it be worth to also remove the image and redownload it in this case?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/38)*

**Comment by Page-** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/application.coffee, line 223 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/38#-K4ZGv4ynq1ApVcAb8wy:-K4ZHeTYDjqc5tms9P8t:-1006246160) ([raw file](https://github.com/resin-io/resin-supervisor/blob/f0afdb9b2a04b5da39420eaafea34be3a188bf08/src/application.coffee#L223)):*
That will help for cases where the downloaded image in corrupt, but in others it will be because the image itself has an issue (eg the CMD points to a file that doesn't exist)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/38)*

**Comment by pcarranzav** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/application.coffee, line 223 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/38#-K4ZGv4ynq1ApVcAb8wy:-K4ZIMpKruNnmF7EEvbR:1501234864) ([raw file](https://github.com/resin-io/resin-supervisor/blob/f0afdb9b2a04b5da39420eaafea34be3a188bf08/src/application.coffee#L223)):*
Alright, we leave it like this then

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/38)*

**Comment by Page-** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/38)*

**Pull request merged**
