### PR TITLE
WIP: Bind mount kmod if the container is debian or raspbian

### PR DESCRIPTION
**Pull request by pcarranzav**
connects to #204 

---
This change is [Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/205)

### CODE REVIEW

**Comment by Page-** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/application.coffee, line 173 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205#-KM_RbVUWI0RQqDYNCAZ:-KM_RbVVJJCcGwv6CijD:-2089287972) ([raw file](https://github.com/resin-io/resin-supervisor/blob/3abec6be013d414f80859176cc5a31ab9b97df5e/src/application.coffee#L173)):*
> ```CoffeeScript
> 		utils.getOSVersion(rootDir + '/etc/os-release')
> 	.then (version) ->
> 		if version? and (version.match(/^Debian/) or version.match(/^Raspbian/))
> ```

It's probably worth using `/../i` to do case insensitive matching

---

*[src/application.coffee, line 173 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205#-KM_RlLk48xiFYmukHBr:-KM_RlLk48xiFYmukHBs:265958317) ([raw file](https://github.com/resin-io/resin-supervisor/blob/3abec6be013d414f80859176cc5a31ab9b97df5e/src/application.coffee#L173)):*
> ```CoffeeScript
> 		utils.getOSVersion(rootDir + '/etc/os-release')
> 	.then (version) ->
> 		if version? and (version.match(/^Debian/) or version.match(/^Raspbian/))
> ```

You can just do `return version? and ...`

---

*[src/utils.coffee, line 197 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205#-KM_SByA2fWjVJ9ZKX2f:-KM_SByA2fWjVJ9ZKX2g:-35546433) ([raw file](https://github.com/resin-io/resin-supervisor/blob/3abec6be013d414f80859176cc5a31ab9b97df5e/src/utils.coffee#L197)):*
> ```CoffeeScript
> 	fs.readFileAsync(path)
> 	.then (releaseData) ->
> 		lines = (new String(releaseData)).split('\n')
> ```

Does it make sense to use `fs.readFileAsync(path, 'utf8')` to avoid this? Or alternatively use the `Buffer::toString` method as `releaseData.toString()`?

---

*[src/utils.coffee, line 206 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205#-KM_bDGlQ5LbuJf0IIeP:-KM_bDGlQ5LbuJf0IIeQ:-950734644) ([raw file](https://github.com/resin-io/resin-supervisor/blob/3abec6be013d414f80859176cc5a31ab9b97df5e/src/utils.coffee#L206)):*
> ```CoffeeScript
> 	.catch (err) ->
> 		console.log('Could not get OS Version: ', err, err.stack)
> 		return undefined
> ```

There's no need to specify undefined

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205)*

**Comment by pcarranzav** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/application.coffee, line 173 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205#-KM_RbVUWI0RQqDYNCAZ:-KM_gh8dmI5JgDGHhiC-:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/3abec6be013d414f80859176cc5a31ab9b97df5e/src/application.coffee#L173)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> It's probably worth using `/../i` to do case insensitive matching
</details>
Done.

---

*[src/application.coffee, line 173 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205#-KM_RlLk48xiFYmukHBr:-KM_ghnqU7Nwbm5Tyehf:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/3abec6be013d414f80859176cc5a31ab9b97df5e/src/application.coffee#L173)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> You can just do `return version? and ...`
</details>
Done.

---

*[src/utils.coffee, line 197 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205#-KM_SByA2fWjVJ9ZKX2f:-KM_gihTyBbQu6xmP342:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/3abec6be013d414f80859176cc5a31ab9b97df5e/src/utils.coffee#L197)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> Does it make sense to use `fs.readFileAsync(path, 'utf8')` to avoid this? Or alternatively use the `Buffer::toString` method as `releaseData.toString()`?
</details>
Done.

---

*[src/utils.coffee, line 206 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205#-KM_bDGlQ5LbuJf0IIeP:-KM_gj8hCvKpoHcgsvT1:-845613445) ([raw file](https://github.com/resin-io/resin-supervisor/blob/3abec6be013d414f80859176cc5a31ab9b97df5e/src/utils.coffee#L206)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> There's no need to specify undefined
</details>
I'd rather specify it to make it explicit that this is what we return in case of an error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205)*

**Comment by Page-** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205)*

**Comment by Page-** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/docker-utils.coffee, line 310 \[r3\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205#-KMkGxTU3bTUyxpYm_bF:-KMkGxTU3bTUyxpYm_bG:1172618636) ([raw file](https://github.com/resin-io/resin-supervisor/blob/812e56f32c4d779cc58bf585b6780953db0c2459/src/docker-utils.coffee#L310)):*
> ```CoffeeScript
> 			res.status(500).send(err?.message or err or 'Unknown error')
> 
> 	exports.imageRootDir = (image) ->
> ```

Wouldn't it be better to have callers just do `docker.imageRootDir` directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205)*

**Comment by pcarranzav** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/docker-utils.coffee, line 310 \[r3\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205#-KMkGxTU3bTUyxpYm_bF:-KMkwj-3v06Ndk8W8S8h:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/812e56f32c4d779cc58bf585b6780953db0c2459/src/docker-utils.coffee#L310)):*
<details><summary><i>Previously, Page- wrote…</i></summary>
> Wouldn't it be better to have callers just do `docker.imageRootDir` directly?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205)*

**Comment by Page-** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/205)*

**Comment by petrosagg** [comment]
SGTM

**Comment by pcarranzav** [comment]
Tested with alpine and debian base images, modprobe works in both.

**Pull request merged**
