### PR TITLE
Add proxy support and CA Root Cert

### PR DESCRIPTION
**Pull request by axbannaz**
Adding proxy suport and CA Root certs additions in to runing supervisor image.
       Integrating http_proxy https_proxy environment variables into docker build and final docker image
       Remove go build run containers
       adding support to include internal CA Certs used by (an example) proxy servers

---
This change is [Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/185)

### CODE REVIEW

**Comment by pcarranzav** [comment]
Thanks @axbannaz !
LGTM but I'd like a second opinion, maybe @Page- or @petrosagg ?

**Comment by pcarranzav** [comment]
@resin-jenkins test this please

**Comment by lifeeth** [comment]
*[Makefile, line 89 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185#-KLV9zmPyqH6MJu5D13P:-KLV9zmPyqH6MJu5D13Q:1912214318) ([raw file](https://github.com/resin-io/resin-supervisor/blob/324d187dc31e30f54c798bf2a0fb71b757d1d0f7/Makefile#L89)):*
> ```Makefile
> 	echo "ENV DEFAULT_MIXPANEL_TOKEN $(MIXPANEL_TOKEN)" >> Dockerfile
> ifdef https_proxy
> 	echo "ENV HTTPS_PROXY $(https_proxy)" >> Dockerfile
> ```

Build time HTTP/HTTPS proxy configurations become run time proxy configurations. There should be a clear separation between the two.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185)*

**Comment by lifeeth** [comment]
*[tools/dind/Dockerfile, line 19 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185#-KLVAGue_J7isNR7H14A:-KLVAGue_J7isNR7H14B:1508690435) ([raw file](https://github.com/resin-io/resin-supervisor/blob/324d187dc31e30f54c798bf2a0fb71b757d1d0f7/tools/dind/Dockerfile#L19)):*
> ```Dockerfile
> ENV PASSWORDLESS_DROPBEAR false
> 
> COPY config/certs/ /usr/local/share/ca-certificates/
> ```

I believe this also needs a separation as run time and build time. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185)*

**Comment by pcarranzav** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[Makefile, line 89 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185#-KLV9zmPyqH6MJu5D13P:-KLXAh2mx45Jn9ymKhl8:393452783) ([raw file](https://github.com/resin-io/resin-supervisor/blob/324d187dc31e30f54c798bf2a0fb71b757d1d0f7/Makefile#L89)):*
<details><summary><i>Previously, lifeeth (Praneeth) wrote…</i></summary>
> Build time HTTP/HTTPS proxy configurations become run time proxy configurations. There should be a clear separation between the two.
</details>
Good point.
I'd say this could just be handled with a boolean, i.e. wrap all of this in something like `ifdef use_proxy_at_runtime` in case a user wants to use the same proxy for build and runtime.
Then if a user wants a *different* proxy at runtime, they can just pass it as an env var when starting the supervisor container, which seems more appropriate.

---

*[tools/dind/Dockerfile, line 19 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185#-KLVAGue_J7isNR7H14A:-KLXBJATc4yYZiLK-RdY:1090071608) ([raw file](https://github.com/resin-io/resin-supervisor/blob/324d187dc31e30f54c798bf2a0fb71b757d1d0f7/tools/dind/Dockerfile#L19)):*
<details><summary><i>Previously, lifeeth (Praneeth) wrote…</i></summary>
> I believe this also needs a separation as run time and build time. 
</details>
Hmm I think this *is* just runtime, that is, these certificates will only affect the dind container in the `run-supervisor` make target. Looks fine to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185)*

**Comment by axbannaz** [comment]
*[Makefile, line 89 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185#-KLV9zmPyqH6MJu5D13P:-KLXRLwcnmVlXBUvuLo6:1390722040) ([raw file](https://github.com/resin-io/resin-supervisor/blob/324d187dc31e30f54c798bf2a0fb71b757d1d0f7/Makefile#L89)):*
<details><summary><i>Previously, axbannaz (Arash) wrote…</i></summary>
> Usually the same proxy settings are used for build and runtime..  although, i can see that one can build in one location and run in another.  however, if it was to use a flag to set the runtime proxy, should it have the option to set a different proxy than the build proxy as well?
</details>
Added couple of commits to address this issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185)*

**Comment by axbannaz** [comment]
*[tools/dind/Dockerfile, line 19 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185#-KLVAGue_J7isNR7H14A:-KLbXWmN570DlBi_6N4q:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/324d187dc31e30f54c798bf2a0fb71b757d1d0f7/tools/dind/Dockerfile#L19)):*
<details><summary><i>Previously, pcarranzav (Pablo Carranza Vélez) wrote…</i></summary>
> Hmm I think this *is* just runtime, that is, these certificates will only affect the dind container in the `run-supervisor` make target. Looks fine to me.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185)*

**Comment by axbannaz** [comment]
*[Makefile, line 89 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185#-KLV9zmPyqH6MJu5D13P:-KLbXa1mM11VeO3f0GrW:-499146009) ([raw file](https://github.com/resin-io/resin-supervisor/blob/324d187dc31e30f54c798bf2a0fb71b757d1d0f7/Makefile#L89)):*
<details><summary><i>Previously, axbannaz (Arash) wrote…</i></summary>
> Added couple of commits to address this issue.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185)*

**Comment by Page-** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185)*

**Comment by pcarranzav** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/185)*

**Comment by pcarranzav** [comment]
Need @lifeeth to mark the discussions resolved and we're good to go I think.

**Comment by pcarranzav** [comment]
Thanks @axbannaz !

**Comment by axbannaz** [comment]
Nice, Thanks Guys :)

**Pull request merged**
