### PR TITLE
[WIP] Reduction of memory usage

### PR DESCRIPTION
**Pull request by splitice**
Resolving issue #690

Front logo [Front conversations](https://app.frontapp.com/open/top_d0ur)

### CODE REVIEW

**Comment by shaunmulligan** [comment]
@CameronDiver whats the status on this PR, is their a built image i could test on?

**Comment by CameronDiver** [comment]
@shaunmulligan I've pushed this up to my dockerhub account for the time being, circle doesn't like to push images from external contributions: `0xcd/halleyassist:master`

**Comment by shaunmulligan** [comment]
sweet, thanks @CameronDiver I'll give it a spin

**Comment by shaunmulligan** [comment]
@CameronDiver been playing around with this for the last few days on a RPI3 and it seems pretty stable, haven't seen any adverse behaviour. The supervisor consistently runs at like 37 - 40 MB which is a pretty nice improvement. So from my side I think Im happy for us to include these changes.

**Comment by CameronDiver** [comment]
Hey @splitice sorry for the delay. We had some issues with our merging software (versionbot) related to external contributions. This should be fixed now as we've went to versionbot v2 - so I'm very keen to get this merged now!

Could you rebase on current master, and give me another ping, and we'll get it merged :)

**Comment by shaunmulligan** [comment]
I'm pretty excited to get this merged, have been running it for a few days and it reduces the supervisor memory down to about ~30MB from ~70MB before.

**Comment by splitice** [comment]
@CameronDiver done.

**Comment by CameronDiver** [comment]
Hmm I'm not too sure what's going on here, there's two extra merge commits now, weird.

Did you do
```
git remote add upstream git@github.com:resin-io/resin-supervisor
git fetch upstream
git rebase -i upstream/master
```
?

Also could you you rename the commit to be something slightly more descriptive, then I think we'll be ready to get this merged :)

**Comment by splitice** [comment]
@CameronDiver This was done using the single click github button.

You all have access to the PR. Feel free to modify to comply with whatever standards you wish.

**Comment by CameronDiver** [comment]
@splitice Sorry about the closing of the PR, github got quite confused with the rebase. Opened in https://github.com/resin-io/resin-supervisor/pull/739, thanks for the contribution!

**Pull request closed without merging**
