### PR TITLE
Remove the old terminal code

### PR DESCRIPTION
**Pull request by Page-**
connects to #130 
It has since been made unnecessary by terminal v2, and removing it shrinking the supervisor by around 35.6MB (for the i386 version at least)

---
This change is [Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/128)

### CODE REVIEW

**Comment by emirotin** [comment]
There are also static files for tty.js in lib/static

**Comment by Page-** [comment]
Thanks, I've removed them now

**Comment by pcarranzav** [comment]
Can you also remove those endpoints from [docs/API.md](https://github.com/resin-io/resin-supervisor/blob/master/docs/API.md#post-v1spawn-tty) ?

---

Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/128#-:-KFQP9_uUI01qdy-zqBX:-2000968231)*

**Comment by Page-** [comment]
done

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/128#-:-KFR3U6xhK8xrcNMnJYx:677588487)*

**Comment by pcarranzav** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/resin-io/resin-supervisor/128)*

**Comment by pcarranzav** [comment]
:lgtm:

**Pull request merged**
