### PR TITLE
Add RESIN_SUPERVISOR_DELTA to vars that don't restart the app

### PR DESCRIPTION
**Pull request by pcarranzav**
connects to #103

---
This change is [Review on Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/105)

### CODE REVIEW

**Comment by Page-** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/application.coffee, line 322 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/105#-KCQicfKmc38cnf5su5X:-KCQicfKmc38cnf5su5Y:628628476) ([raw file](https://github.com/resin-io/resin-supervisor/blob/f29bab0b9de7cea225b587f493436e63853ba61e/src/application.coffee#L322)):*
Does this stop the env var being exposed to the container as well?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/105)*

**Comment by pcarranzav** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/application.coffee, line 322 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/105#-KCQicfKmc38cnf5su5X:-KCQkXwRGIC43tEwFyAL:676933147) ([raw file](https://github.com/resin-io/resin-supervisor/blob/f29bab0b9de7cea225b587f493436e63853ba61e/src/application.coffee#L322)):*
Nope

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/105)*

**Comment by Page-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/application.coffee, line 322 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/105#-KCQicfKmc38cnf5su5X:-KCQqrG74BBBarRvEYy9:1138355799) ([raw file](https://github.com/resin-io/resin-supervisor/blob/f29bab0b9de7cea225b587f493436e63853ba61e/src/application.coffee#L322)):*
Ok, I guess we need to document that it cannot be relied upon to always be correct - if it changes whilst the container is running then it will show the out of date value

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/105)*

**Comment by pcarranzav** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/application.coffee, line 322 \[r1\]](https://reviewable.io:443/reviews/resin-io/resin-supervisor/105#-KCQicfKmc38cnf5su5X:-KCR-ZItZ0oVfUEFcAug:-2118624741) ([raw file](https://github.com/resin-io/resin-supervisor/blob/f29bab0b9de7cea225b587f493436e63853ba61e/src/application.coffee#L322)):*
Indeed. I guess it's something to be added in [#87](https://github.com/resin-io/resin-supervisor/issues/87)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/resin-io/resin-supervisor/105)*

**Pull request merged**
