### PR TITLE
Update waffle badge

### PR DESCRIPTION
**Pull request by sks**
Replace space with ` %20 `

---
This change is [Reviewable](https://reviewable.io/reviews/resin-io/resin-supervisor/400)

### CODE REVIEW

**Comment by sks** [comment]
Before:
screen shot 2017-03-21 at 9 01 05 am

After:
screen shot 2017-03-21 at 9 00 49 am

**Comment by pcarranzav** [comment]
@sks just a detail: could you amend your commit to include this in the message?
```
Change-Type: patch
Signed-off-by: name <email>
```
(you can use `-s` in `git commit` for the second one)

**Comment by sks** [comment]
@pcarranzav : Sorry for the delay , Done & Thanks for the tip

**Comment by pcarranzav** [comment]
You did, thanks a lot @sks !

**Pull request merged**
